import { SinglePost } from "@/components/Post/SinglePost";
import { getAllPosts } from "@/lib/notionAPI";
import Head from "next/head";

type Post = {
  id: string;
  title: string;
  description: string;
  data: string;
  slug: string;
  tags: string[];
};

export const getStaticProps = async () => {
  const allPosts = await getAllPosts();

  return {
    props: {
      allPosts,
    },
    revalidate: 60,
  };
};

export default function Home({ allPosts }: any) {
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion-blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container w-full my-16">
        <h1 className="text-5xl font-medium text-center mb-16">
          Notion Blog🚀
        </h1>
        {allPosts.map((post: Post) => (
          <div className="mx-4" key={post.id}>
            <SinglePost post={post} />
          </div>
        ))}
      </main>
    </div>
  );
}
